### ISSUE TITLE
[Bug]: Team owner removal

### ISSUE THREAD

**Issue by Renc17** [ConduitPlatform/Conduit#1095]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ConduitPlatform/Conduit/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [Issue Tracker](https://github.com/ConduitPlatform/Conduit/issues) for a bug that matches the one I want to file, without success.
- [X] This issue is not related to [Conduit Admin Panel](https://github.com/ConduitPlatform/Conduit-UI).
- [X] This issue is not related to [Conduit CLI](https://github.com/ConduitPlatform/CLI).

### Conduit version

0.16.8

### Describe the Bug

A team member with editAll role can delete a team owner.

### Expected Behavior

No one can delete a team owner other than another team owner or someone with specific permission to delete one.

### How to Reproduce

1. Invite another user to a team you own with editAll role (e.x UserWithEditAllRole)
2. Login with UserWithEditAllRole credentials
3. Call DELETE /authentication/teams/{teamId}/members
    Query Parameters - members: [ 'TeamOwnerId' ]

**Comment by ChrisPdgn** [comment]
done in #1097

**Comment by ChrisPdgn** [comment]
done in #1097
