### ISSUE TITLE
[Feature]:  Security Clients add custom name or notes

### ISSUE THREAD

**Issue by running-grass** [ConduitPlatform/Conduit#192]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ConduitPlatform/Conduit/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [Issue Tracker](https://github.com/ConduitPlatform/Conduit/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

When I have several clientids used in different places (eg. apollographql studio, postman, ci), I don't know which one to delete. When I have several clientids used in different places, I don't know which one to delete

**Comment by kon14** [comment]
That actually sounds like a nice feature to have.

**Comment by kkopanidis** [comment]
Sounds useful, @kon14 can you add it to the backlog for the next release?

**Comment by kkopanidis** [comment]
@running-grass waiting for front-end to implement this, backend is already updated. Release 0.13.0-rc1 will include this
