### ISSUE TITLE
[Feature]: Local Storage support url

### ISSUE THREAD

**Issue by running-grass** [ConduitPlatform/Conduit#195]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ConduitPlatform/Conduit/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [Issue Tracker](https://github.com/ConduitPlatform/Conduit/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

when I use local storage provider, i can't get saved files. Neither base64 data nor url.

**Comment by kkopanidis** [comment]
The url methods are not implemented for the local storage provider. This is meant to be used like a development setting, but I understand how this can be limiting. Can you describe what is happening with base64 though? I'm assuming you're using the /storage/file/data/:id endpoint.

**Comment by running-grass** [comment]
my described was wrong,（Excuse me for bad English!)
i mean to say ,   It would be nice to support data urls when http urls are not supported
