### ISSUE TITLE
[Bug]: Cannot start on windows 

### ISSUE THREAD

**Issue by heromiyo** [ConduitPlatform/Conduit#209]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ConduitPlatform/Conduit/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [Issue Tracker](https://github.com/ConduitPlatform/Conduit/issues) for a bug that matches the one I want to file, without success.
- [X] This issue is not related to the [Conduit Admin Panel](https://github.com/ConduitPlatform/Conduit-UI) user interface.

### Conduit version

latest

### Describe the Bug

 make zero-to-hero

Initializing Conduit Container Environment ðŸ”¨
This may take a while. Better bring up Reddit ðŸ˜…
------------------------------------------------
make[2]: *** [Makefile:59: create-network] Error 1
make[1]: *** [Makefile:51: setup] Error 2
make: *** [Makefile:38: zero-to-hero] Error 2

### Expected Behavior

should start services 

### How to Reproduce

1. mkdir conduit
2. cd conduit
3. source <(curl -s https://getconduit.dev/bootstrap)
4. make zero-to-setup

### Additional Information

CMD
![image](https://user-images.githubusercontent.com/39757927/173921861-3fde5ada-bc39-4337-86c6-c041f4536045.png)

git bash
![image](https://user-images.githubusercontent.com/39757927/173921928-3f2eb8a2-8716-4617-b107-62c12481db35.png)

### Environment

windows 10

**Comment by kon14** [comment]
Thanks for reporting this. I guess you're missing `/dev/null`.
Have you tried running this through WSL (with a configured Docker connection)?

We are currently in the process of packaging [our cli](https://github.com/ConduitPlatform/CLI) that's going to improve upon this as well as offer additional dev features unrelated to bootstrapping.

**Comment by heromiyo** [comment]
Even using wsl fails @kon14 
![image](https://user-images.githubusercontent.com/39757927/174190351-53251d61-2021-4bf6-8f2b-61327c1e985b.png)

**Comment by kkopanidis** [comment]
@heromiyo allow us some time to look into this, and we'll get back to you!

**Comment by heromiyo** [comment]
worked by wsl, cloned the whole repo into wsl
