### ISSUE TITLE
[Feature]: Update Discord invite link

### ISSUE THREAD

**Issue by shwarcu** [ConduitPlatform/Conduit#323]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ConduitPlatform/Conduit/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [Issue Tracker](https://github.com/ConduitPlatform/Conduit/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

![discord](https://user-images.githubusercontent.com/58426925/189730279-57f35d9e-d383-44c6-b105-d20cc251758f.PNG)

When creating a new issue there is an option to join Discord server. When I open the link, it says that invitation link is invalid.

**Comment by kkopanidis** [comment]
Hey @shwarcu, thanks for noticing! We've updated the link, I'm also pasting it here so you can use it if you want: https://discord.gg/hWnW2aJDrE .

Have a nice day.
