### ISSUE TITLE
[Bug]: Deleting Schema doesn't remove api from Swagger

### ISSUE THREAD

**Issue by the-ssd** [ConduitPlatform/Conduit#413]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ConduitPlatform/Conduit/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [Issue Tracker](https://github.com/ConduitPlatform/Conduit/issues) for a bug that matches the one I want to file, without success.
- [X] This issue is not related to the [Conduit Admin Panel](https://github.com/ConduitPlatform/Conduit-UI) user interface.

### Conduit version

0.15.3

### Describe the Bug

in Swagger (JSON and UI) are schemas that are deleted or CRUD was changed and not all CRUD operations are available

- [ ] 

### Expected Behavior

Remove not available APIs when CRUD changed or schema is deleted

### How to Reproduce

1. deploy setup
2. create schema
3. set any CRUD to enable
4. check if Swagger added API
5. delete schema or disable any CRUD
6. Swagger has API entries that don't exist

### Environment

Endevuor OS (Arch Linux)

**Comment by kkopanidis** [comment]
Thanks for bringing this up @the-ssd. Do the endpoints work though? I'm trying to understand if this is swagger-only or if the router does not clean up properly in some case. So if you try to call an endpoint that should have been removed do you get a 404 error or a 500 error?
