### ISSUE TITLE
[Bug]: [AUTH] Access token not rejected when user is blocked

### ISSUE THREAD

**Issue by IshFx** [ConduitPlatform/Conduit#592]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ConduitPlatform/Conduit/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [Issue Tracker](https://github.com/ConduitPlatform/Conduit/issues) for a bug that matches the one I want to file, without success.
- [X] This issue is not related to [Conduit Admin Panel](https://github.com/ConduitPlatform/Conduit-UI).
- [X] This issue is not related to [Conduit CLI](https://github.com/ConduitPlatform/CLI).

### Conduit version

0.15.15

### Describe the Bug

When a user is blocked from the admin panel, he can still call all endpoints (expect login) because the JWT is still active.

### Expected Behavior

When a user is blocked, its associated JWT should be blacklisted.

### How to Reproduce

1. Create a user
2. Login
3. Query a db document for example (it should work)
4. Block user
5. Query a db document for example (it SHOULDN'T work)

**Comment by kkopanidis** [comment]
Thanks for the report @IshFx ! I've opened #593, will merge tomorrow and release a new verison

**Comment by IshFx** [comment]
Thanks for the quick fix !
