### ISSUE TITLE
[Bug]: Error when using SMTP email provider

### ISSUE THREAD

**Issue by Grouptag-Mukil** [ConduitPlatform/Conduit#610]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ConduitPlatform/Conduit/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [Issue Tracker](https://github.com/ConduitPlatform/Conduit/issues) for a bug that matches the one I want to file, without success.
- [X] This issue is not related to [Conduit Admin Panel](https://github.com/ConduitPlatform/Conduit-UI).
- [X] This issue is not related to [Conduit CLI](https://github.com/ConduitPlatform/CLI).

### Conduit version

0.15.16

### Describe the Bug

when sending an email with an SMTP setup (I am using Gmail), it fails with the following error code:
`[ERROR]: Missing credentials for "PLAIN" Error: Missing credentials for "PLAIN"`

smtp set up used is as follows:
Host: smtp.gmail.com
Port: 587
method: PLAIN

### Expected Behavior

Email successfully sends

### How to Reproduce

1. configure smtp with parameters described
2. send test email
3. observe

### Environment

Ubuntu 20.04 (LTS)

**Comment by kkopanidis** [comment]
Hello @Grouptag-Mukil here as well, you are adding username password correct?

**Comment by Grouptag-Mukil** [comment]
yeah, username and password were used
