### ISSUE TITLE
[BUG] File Storage upload (~3mb) returns 413 'Request Entity Too Large'

### ISSUE THREAD

**Issue by JohnChantz** [ConduitPlatform/Conduit#84]
**Describe the bug**
When uploading an image to file storage of conduit, for images > ~3mb then the api returns status code 413

**To Reproduce**
1. Try to upload a new image to conduit file storage
2. For images > 3mb of size
3. The api call returns status code 413 request entity too large

**Expected behavior**

**Screenshots**

**Additional context**
 - Conduit version: 0.10.6

**Comment by kkopanidis** [comment]
Closing issue, since this was in fact an Nginx error.
