### ISSUE TITLE
[Bug]: Configuring Github and gitlab as OAuth provider is swapped

### ISSUE THREAD

**Issue by haexhub** [ConduitPlatform/Conduit#847]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ConduitPlatform/Conduit/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [Issue Tracker](https://github.com/ConduitPlatform/Conduit/issues) for a bug that matches the one I want to file, without success.
- [X] This issue is not related to [Conduit Admin Panel](https://github.com/ConduitPlatform/Conduit-UI).
- [X] This issue is not related to [Conduit CLI](https://github.com/ConduitPlatform/CLI).

### Conduit version

0.15.15

### Describe the Bug

If you try to configure github as OAuth provider in ```authentication/signIn``` and hit save, the configuration is applied to gitlab instead of github and vice versa.

### Expected Behavior

Configuring github as OAuth provider should be applied to github and not gitlab and vice versa.

### How to Reproduce

1. spin up your [docker environment](https://github.com/ConduitPlatform/Conduit/tree/main/docker)
2. sign in your app and goto [Auth Providers](http://localhost:8080/authentication/signIn)
3. try to configure github
4. you will see, if you hit save, your configuration will be applied to gitlab

**Comment by kon14** [comment]
Hello and thanks for taking the time to report this.
We recently discovered this and have [pushed a fix](https://github.com/ConduitPlatform/Conduit-UI/commit/f2a1536caf7fa624a2ec51d0aca27ea3c359e884) in Conduit-UI.

We simply forgot to release a new UI version for it, but we'll do it now.
Once again, thanks for letting us know about this!

**Comment by kkopanidis** [comment]
Hi @haexhub new release v0.15.15 for the UI is being built, should work correctly once you pull the new UI image

**Comment by haexhub** [comment]
thank you for your quick response. I checked the new release and it works now :)
