### ISSUE TITLE
[Bug]: OAuth Url has a surplus question mark 

### ISSUE THREAD

**Issue by haexhub** [ConduitPlatform/Conduit#854]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ConduitPlatform/Conduit/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [Issue Tracker](https://github.com/ConduitPlatform/Conduit/issues) for a bug that matches the one I want to file, without success.
- [X] This issue is not related to [Conduit Admin Panel](https://github.com/ConduitPlatform/Conduit-UI).
- [X] This issue is not related to [Conduit CLI](https://github.com/ConduitPlatform/CLI).

### Conduit version

0.15.15

### Describe the Bug

Hi conduit team.

I found a little bug in your url for OAuth providers. If you start the auth flow with ```http://localhost:3000/authentication/init/github``` for example, you construct a login url to github, which looks like this ```https://github.com/login/oauth/authorize??client_id=4a66c55...``` (2 question marks).
Could you please correct this and remove the excess question mark?

### Expected Behavior

The login url should only contain 1 question mark
```https://github.com/login/oauth/authorize?client_id=4a66c55...```

### How to Reproduce

Just spin up your Conduit App and goto ```http://localhost:3000/swagger/#/authentication/get_authentication_init_github``` and start the auth flow. You will see in the response the wrong url.

**Comment by kkopanidis** [comment]
Hi @haexhub thank you for another spot-on issue, we fixed the issue on the main branch, and will propagate shortly on 0.15. Keep an eye out for a new version.

**Comment by haexhub** [comment]
Thanks again. You are amazing and incredible fast with responses. :smile: 
I like it :partying_face:
