### ISSUE TITLE
[BUG] Proto files don't respect official style guide

### ISSUE THREAD

**Issue by kon14** [ConduitPlatform/Conduit#86]
**Describe the bug**
While not necessarily breaking anything, Conduit should make sure its proto files abide by the [official Protocol Buffers style guide](https://developers.google.com/protocol-buffers/docs/style).
I have yet to cross-check every single one of them, but at a first glance, it seems like we're mostly ignoring case conventions.
Namely snake_case for files (eg `push-notifications.proto`) and, sometimes, CamelCase for services and rpcs (eg Database's `rpc findOne`).

**Expected behavior**
Conduit's proto files should respect the official style guide, making sure they follow case conventions etc.

**Comment by kkopanidis** [comment]
Yeah the solution seems to require quite a bit of refactoring. I'm trying to understand if we tangled ourselves into this mess or it was bound to get messy either way. We'll need to have a design meeting on discord for this to figure out a proper approach to untangle this thing.
