### ISSUE TITLE
[BUG] RoutingManager stringifies strings

### ISSUE THREAD

**Issue by kon14** [ConduitPlatform/Conduit#91]
**Describe the bug**
RoutingManager sometimes ends up stringifying strings.
One instance of this is Chat's socket path ending up as `/chat/"/"`.

Marking this for proper testing.

**Comment by kkopanidis** [comment]
I think this was caused solely by the Routing manager, but I'll investigate the stringify usage in general to see if any other utility causes it also.

**Comment by kkopanidis** [comment]
fixed on #94
